apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: mykafka-source
spec:
  consumerGroup: my-group
  bootstrapServers: my-cluster-kafka-bootstrap.kafka-analytics:9092 
  topics: my-topic
  sink: 
   ref:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: eventinghello
